linting, eslint and jsconfig
sandeepscet/prompt-apps pull request #9
Opened 2023-04-28 15:32 UTC by dangus21

By submitting a PR to this repository, you agree to the terms within the [Code of Conduct](../CODE-OF-CONDUCT.md). Please see the [contributing guidelines](../CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Added paths to jsconfig
> Added eslint config

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

2023-04-29 05:53 UTC, sandeepscet requested changes

2023-04-29 05:53 UTC, sandeepscet commented on .eslintrc.js
> +} = require("@angusmiguel/es-configs");
Dependency for eslint on another project can create maintenance issues, specially not much used.
Please add those dependency direct into this project.

2023-04-29 19:10 UTC, dangus21 commented on .eslintrc.js
> +} = require("@angusmiguel/es-configs");
updated! :)

2023-04-29 19:11 UTC, dangus21 commented on .eslintrc.js
> +} = require("@angusmiguel/es-configs");
also, changed to package manager to pnpm for faster installs

2023-05-01 05:42 UTC, sandeepscet approved these changes

2023-05-01 05:42 UTC, merged